name: Weekly

on:
  schedule:
    - cron:  '0 0 * * 3'
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:horus-stable

    steps:
    - name: Install git
      run: |
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install git -y

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Build metadata
      run: |
        ./build.sh jammy stable

    - name: Push metadata
      run: |
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        git add .
        git commit -m "Automatic update of metadata"
        git push
      env:
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
