name: Weekly

on:
  schedule:
    - cron:  '0 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:stable

    steps:
    - name: Clone repository
      uses: actions/checkout@v1

    - name: Build metadata
      run: |
        ln -s $GITHUB_WORKSPACE /repo
        ./build.sh focal stable

    - name: Push metadata
      run: |
        ./commit.sh
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
