name: Weekly

on:
  schedule:
    - cron:  '0 0 * * 3'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:stable

    steps:
    - name: Clone repository
      uses: actions/checkout@v1

    - name: Build metadata
      run: |
        ln -s $GITHUB_WORKSPACE /repo
        ./build.sh bionic stable

    - name: Push metadata
      run: |
        ./commit.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

